CREATE DATABASE BD_IMPUESTOS_MUNICIPALES;
USE BD_IMPUESTOS_MUNICIPALES;

CREATE TABLE OFICINA
(
ID_OFICINA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COD INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DNI INT(8) NOT NULL UNIQUE,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
CARGO VARCHAR(45) NOT NULL,

ID_OFICINA INT NOT NULL,
CONSTRAINT FK_ID_OFICINA FOREIGN KEY (ID_OFICINA)
REFERENCES OFICINA(ID_OFICINA)
);

CREATE TABLE ROL
(
ID_ROL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(35) NOT NULL,
DESCRIPCION VARCHAR(100)
);

CREATE TABLE MODULO
(
ID_MODULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(35) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE ROL_MODULO
(
ID_ROL_MODULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_ROL INT NOT NULL,
ID_MODULO INT NOT NULL,
ESTADO BOOLEAN NOT NULL,
CONSTRAINT FK_ID_ROL FOREIGN KEY(ID_ROL)
REFERENCES ROL(ID_ROL),
CONSTRAINT FK_ID_MODULO FOREIGN KEY(ID_MODULO)
REFERENCES MODULO(ID_MODULO)
);

CREATE TABLE USUARIO
(
ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CUENTA VARCHAR(12) NOT NULL,
CLAVE VARCHAR(12) NOT NULL,
ESTADO BOOLEAN,
ID_ROL INT NOT NULL,

CONSTRAINT FK_ID_USUARIO FOREIGN KEY(ID_USUARIO)
REFERENCES EMPLEADO(ID_EMPLEADO),
CONSTRAINT FK_ID_ROL_USUARIO FOREIGN KEY(ID_ROL)
REFERENCES ROL(ID_ROL)
);

CREATE TABLE SERVICIO
(
ID_SERVICIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
TARIFA DOUBLE NOT NULL,
RUBRO VARCHAR(50) NOT NULL
);

CREATE TABLE PERSONA_NATURAL
(
ID_PERSONA_NATURAL INT NOT NULL PRIMARY KEY,
DNI INT(8) NOT NULL UNIQUE,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO_PA VARCHAR(25) NOT NULL,
APELLIDO_MA VARCHAR(25) NOT NULL,
FECHA_NACIMIENTO VARCHAR(20) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
PROFESION VARCHAR(45) NOT NULL,
ESTADO BOOLEAN NOT NULL
);

CREATE TABLE PERSONA_JURIDICO
(
ID_PERSONA_JURIDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
RUC INT(15) NOT NULL UNIQUE,
ID_PERSONA_NATURAL INT NOT NULL,
RAZON_SOCIAL VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(500) NOT NULL,
FECHA_CREACION VARCHAR(10) NOT NULL,
FECHA_MODIFICACION VARCHAR(10),
ESTADO BOOLEAN,

CONSTRAINT FK_ID_PERSONA_NATURAL FOREIGN KEY(ID_PERSONA_NATURAL)
REFERENCES PERSONA_NATURAL(ID_PERSONA_NATURAL)
);

CREATE TABLE TIPO_IDENTIFICACION
(
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL
);

CREATE TABLE IDENTIFICACION_DNI
(
ID_PERSONA_NATURAL INT NOT NULL,
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
CONSTRAINT FK_ID_PERSONA_NATURAL_DNI FOREIGN KEY(ID_PERSONA_NATURAL)
REFERENCES PERSONA_NATURAL(ID_PERSONA_NATURAL),
CONSTRAINT FK_ID_TIPO_IDENTIFICACION_DNI FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE IDENTIFICACION_RUC
(
ID_PERSONA_JURIDICO INT NOT NULL,
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
CONSTRAINT FK_ID_PERSONA_JURIDICO_RUC FOREIGN KEY(ID_PERSONA_JURIDICO)
REFERENCES PERSONA_JURIDICO(ID_PERSONA_JURIDICO),
CONSTRAINT FK_ID_TIPO_IDENTIFICACION_RUC FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE CONTRIBUYENTE 
(
ID_CONTRIBUYENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_TIPO_IDENTIFICACION INT NOT NULL,
NUMERO_TELEFONICO INT(9),
DIRECCION VARCHAR(50) NOT NULL,
REFERENCIA VARCHAR(50),
ESTADO BOOLEAN,

CONSTRAINT FK_TIPO_IDENTIFICACION FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE ESTADO_CONTRATO
(
ID_ESTADO_CONTRATO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE CONTRATO
(
ID_CONTRATO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COD INT(4) NOT NULL UNIQUE,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
IMPUESTO DOUBLE NOT NULL,
ID_SERVICIO INT NOT NULL,
ID_ESTADO_CONTRATO INT NOT NULL,

CONSTRAINT FK_ID_SERVICIO FOREIGN KEY(ID_SERVICIO)
REFERENCES SERVICIO(ID_SERVICIO),
CONSTRAINT FK_ID_ESTADO_CONTRATO FOREIGN KEY(ID_ESTADO_CONTRATO)
REFERENCES ESTADO_CONTRATO(ID_ESTADO_CONTRATO)
);

