CREATE DATABASE BD_IMPUESTOS_MUNICIPALES;
USE BD_IMPUESTOS_MUNICIPALES;

CREATE TABLE OFICINA
(
ID_OFICINA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COD INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DNI INT(8) NOT NULL UNIQUE,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
CARGO VARCHAR(45) NOT NULL,

ID_OFICINA INT NOT NULL,
CONSTRAINT FK_ID_OFICINA FOREIGN KEY (ID_OFICINA)
REFERENCES OFICINA(ID_OFICINA)
);

CREATE TABLE ROL
(
ID_ROL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(35) NOT NULL,
DESCRIPCION VARCHAR(100)
);
INSERT INTO ROL
VALUES
(1, 'Administrador', 'Encargado de administrar todas las funciones del sistema'),
(2, 'Logistica', ''),
(3, 'Recursos Humanos', ''),
(4, 'Operaciones', ''),
(5, 'Planeamiento', '');

CREATE TABLE MODULO
(
ID_MODULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(35) NOT NULL,
DESCRIPCION VARCHAR(100)
);
INSERT INTO MODULO
VALUES
(1, 'Empleado', ''),
(2, 'Contrato', ''),
(3, 'Contribuyente', ''),
(4, 'Oficina', ''),
(5, 'Servicio', ''),
(6, 'Usuario', '');

CREATE TABLE ROL_MODULO
(
ID_ROL_MODULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_ROL INT NOT NULL,
ID_MODULO INT NOT NULL,
ESTADO BOOLEAN NOT NULL,
CONSTRAINT FK_ID_ROL FOREIGN KEY(ID_ROL)
REFERENCES ROL(ID_ROL),
CONSTRAINT FK_ID_MODULO FOREIGN KEY(ID_MODULO)
REFERENCES MODULO(ID_MODULO)
);
INSERT INTO ROL_MODULO
VALUES
/*Administrador*/
(1, 1, 1, 1),
(2, 1, 2, 1),
(3, 1, 3, 1),
(4, 1, 4, 1),
(5, 1, 5, 1),
(6, 1, 6, 1),
/*Logistica*/
(7, 2, 1, 1),
(8, 2, 2, 1),
/*Recursos Humanos*/
(9, 3, 3, 1),
(10, 3, 4, 1),
/*Operaciones*/
(11, 4, 5, 1),
(12, 4, 6, 1),
/*Planeamiento*/
(13, 5, 3, 1),
(14, 5, 4, 1),
(15, 5, 5, 1),
(16, 5, 6, 1);

CREATE TABLE SERVICIO
(
ID_SERVICIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
TARIFA DOUBLE NOT NULL,
RUBRO VARCHAR(50) NOT NULL
);

CREATE TABLE PERSONA_NATURAL
(
ID_PERSONA_NATURAL INT NOT NULL PRIMARY KEY,
DNI INT(8) NOT NULL UNIQUE,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO_PA VARCHAR(25) NOT NULL,
APELLIDO_MA VARCHAR(25) NOT NULL,
FECHA_NACIMIENTO VARCHAR(20) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
PROFESION VARCHAR(45) NOT NULL,
ESTADO BOOLEAN NOT NULL
);

CREATE TABLE PERSONA_JURIDICO
(
ID_PERSONA_JURIDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
RUC INT(15) NOT NULL UNIQUE,
ID_PERSONA_NATURAL INT NOT NULL,
RAZON_SOCIAL VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(500) NOT NULL,
FECHA_CREACION VARCHAR(10) NOT NULL,
FECHA_MODIFICACION VARCHAR(10),
ESTADO BOOLEAN,

CONSTRAINT FK_ID_PERSONA_NATURAL FOREIGN KEY(ID_PERSONA_NATURAL)
REFERENCES PERSONA_NATURAL(ID_PERSONA_NATURAL)
);

CREATE TABLE TIPO_IDENTIFICACION
(
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(15) NOT NULL
);

CREATE TABLE IDENTIFICACION_DNI
(
ID_PERSONA_NATURAL INT NOT NULL,
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
CONSTRAINT FK_ID_PERSONA_NATURAL_DNI FOREIGN KEY(ID_PERSONA_NATURAL)
REFERENCES PERSONA_NATURAL(ID_PERSONA_NATURAL),
CONSTRAINT FK_ID_TIPO_IDENTIFICACION_DNI FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE IDENTIFICACION_RUC
(
ID_PERSONA_JURIDICO INT NOT NULL,
ID_TIPO_IDENTIFICACION INT NOT NULL PRIMARY KEY,
CONSTRAINT FK_ID_PERSONA_JURIDICO_RUC FOREIGN KEY(ID_PERSONA_JURIDICO)
REFERENCES PERSONA_JURIDICO(ID_PERSONA_JURIDICO),
CONSTRAINT FK_ID_TIPO_IDENTIFICACION_RUC FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE CONTRIBUYENTE 
(
ID_CONTRIBUYENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_TIPO_IDENTIFICACION INT NOT NULL,
NUMERO_TELEFONICO INT(9),
DIRECCION VARCHAR(50) NOT NULL,
REFERENCIA VARCHAR(50),
ESTADO BOOLEAN,

CONSTRAINT FK_TIPO_IDENTIFICACION FOREIGN KEY(ID_TIPO_IDENTIFICACION)
REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE ESTADO_CONTRATO
(
ID_ESTADO_CONTRATO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE CONTRATO
(
ID_CONTRATO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COD INT(4) NOT NULL UNIQUE,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
IMPUESTO DOUBLE NOT NULL,
ID_SERVICIO INT NOT NULL,
ID_ESTADO_CONTRATO INT NOT NULL,

CONSTRAINT FK_ID_SERVICIO FOREIGN KEY(ID_SERVICIO)
REFERENCES SERVICIO(ID_SERVICIO),
CONSTRAINT FK_ID_ESTADO_CONTRATO FOREIGN KEY(ID_ESTADO_CONTRATO)
REFERENCES ESTADO_CONTRATO(ID_ESTADO_CONTRATO)
);


/*CREATE TABLE USERS
(
ID INT NOT NULL PRIMARY KEY,
CUENTA VARCHAR(12) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
EMAIL_VERIFIED_AT timestamp,
PASSWORD VARCHAR(12) NOT NULL,
ESTADO BOOLEAN,
ID_EMPLEADO INT NOT NULL,
ID_ROL INT NOT NULL,
REMEMBER_TOKEN ----
CONSTRAINT FK_ID_USUARIO FOREIGN KEY(ID_USUARIO)
REFERENCES EMPLEADO(ID_EMPLEADO),
CONSTRAINT FK_ID_ROL_USUARIO FOREIGN KEY(ID_ROL)
REFERENCES ROL(ID_ROL)
);*/
INSERT INTO USERS
VALUES
(1, 'admin', 'admin@hotmail.com', null ,'$2y$10$dsvG16/tkLMiPJYl7mzdL.Ouvy15YLCsmeREL0vIruE44gSikMV8i', 0, 1, 1, null, current_date(), current_date()),
(2, 'admin2', 'admin2@hotmail.com', null ,'$2y$10$dsvG16/tkLMiPJYl7mzdL.Ouvy15YLCsmeREL0vIruE44gSikMV8i', 0, 2, 2, null, current_date(), current_date()),
(3, 'admin3', 'admin3@hotmail.com', null ,'$2y$10$dsvG16/tkLMiPJYl7mzdL.Ouvy15YLCsmeREL0vIruE44gSikMV8i', 0, 3, 3, null, current_date(), current_date()),
(4, 'admin4', 'admin4@hotmail.com', null ,'$2y$10$dsvG16/tkLMiPJYl7mzdL.Ouvy15YLCsmeREL0vIruE44gSikMV8i', 0, 4, 4, null, current_date(), current_date()),
(5, 'admin5', 'admin5@hotmail.com', null ,'$2y$10$dsvG16/tkLMiPJYl7mzdL.Ouvy15YLCsmeREL0vIruE44gSikMV8i', 0, 5, 5, null, current_date(), current_date());
