insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('LP', 'Limpieza Publica', 'Barrido de calles y avenidas, tambien a la recoleccion y transporte y disposcion final.', '1255', 'Servicios', current_date(), current_date());
insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('MAP', 'Mantenimiento de Areas publicas', 'Mantener en condiciones optimas de limpieza de las calles, plazas, etc.', '2566', 'Servicios', current_date(), current_date());
insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('SC', 'Servicios y Control', 'Se binda el servici de emitir partidas de nacimiento, acta de defunciones,etc, tambien las licencias de conducir, autorizacion de ruta y la administracion del los mercado.', '5144', 'Servicios', current_date(), current_date());
insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('SeG', 'Seguridad Ciudadana', 'Se realizan patrullajes motorizados, esto se desarrolla con la coordinacion junto a la PNP garantizando la seguridad ciudadana', '4666', 'Sevicios', current_date(), current_date());
insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('AP', 'Alumbrado Publico', 'Promoveer la iluminacion necesaria en los espacios publicos, con el fin de garantizar la seguridad de peatones y vehiculos.', '2313', 'Servicio', current_date(), current_date());
insert into `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) values ('AC', 'Administracion del Cementerio', 'Contruimos, habilitamos, conservamos y administramos los cementerios.', '7899', 'Servicio', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`servicio` (`abreviatura`, `nombre`, `descripcion`, `tarifa`, `rubro`, `created_at`, `updated_at`) VALUES ('OP', 'Obras publicas', 'Programa el mantenimiento de los espacios públicos y el mobiliario urbano. Programa y supervisa los diversos proyectos y obras públicas municipales.', '5999', 'Servicios', current_date(), current_date());

insert into `bd_impuestos_municipales`.`oficina` (`cod`, `nombre`, `created_at`, `updated_at`) values ('001', 'Oficina de secretaria general', current_date(), current_date());
insert into `bd_impuestos_municipales`.`oficina` (`cod`, `nombre`, `created_at`, `updated_at`) values ('101', 'Oficina de administracion y finanazas', current_date(), current_date());
insert into `bd_impuestos_municipales`.`oficina` (`cod`, `nombre`, `created_at`, `updated_at`) values ('102', 'Oficina de asesoria juridica', current_date(), current_date());
insert into `bd_impuestos_municipales`.`oficina` (`cod`, `nombre`, `created_at`, `updated_at`) values ('103', 'Oficina de planeamiento y presupuesto', current_date(), current_date());

insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('32541878', 'Miguel Ángel ', 'Burguete García ', 'Jefe de logistica', '2', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('96589632', 'Francisco', 'Caballero Green ', 'Jefe de comunicaciones', '4', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('36584756', 'Juan Gabriel', 'Calvillo Carrasco ', 'Administrador Comercial', '4', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('68547269', 'Erick Fernando ', 'Cano Figueroa ', 'Marketing', '4', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('78946231', 'Ciro ', 'Carrera Santiago ', 'Recursos Humanos', '2', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('65498784', 'Alejandro ', 'Casas Bastida ', 'Administrador de Operaciones', '3', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('32167954', 'Enrique Alfonso ', 'Castillo López ', 'Administrador Comercial', '2', current_date(), current_date());
insert into `bd_impuestos_municipales`.`empleado` (`dni`, `nombre`, `apellido`, `cargo`, `id_oficina`, `created_at`, `updated_at`) values ('32148974', 'Javier Alfredo ', 'Cervantes Gutiérrez ', 'Marketing', '3', current_date(), current_date());

INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('1', '78454578', 'Jose Alfonso', 'Ledesma', 'García', '1978-02-14', 'm', 'Medico', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('2', '54789154', 'Mario Alberto', 'García', 'García', '1988-05-31', 'm', 'Actor', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('3', '63528974', 'Rosa Elena', 'Verdías', 'Gallegos', '1954-12-12', 'f', 'Ganadero', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('4', '98412147', 'Carlos Kukin', 'Sánchez', 'Galindo', '2001-01-01', 'm', 'Maestro', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('5', '65412330', 'Erik', 'Altamirano', 'Fuentes', '1947-05-30', 'm', 'Arquitecto', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('6', '32178998', 'María Antonieta', 'Hernández', 'Forment', '1968-11-18', 'f', 'Bombero', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('7', '98154121', 'Jorge de Jesus', 'Sánchez', 'Flores', '1988-03-20', 'm', 'Dentista', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('8', '74489879', 'Ernesto', 'Mota', 'Franco', '1999-03-26', 'm', 'Cheff', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('9', '65474157', 'Ángel Jesus', 'Estrada', 'Esquivel', '1938-02-16', 'm', 'Diseñador', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('10', '92654124', 'César Luis', 'Bernal', 'Erazo', '1968-08-25', 'm', 'Medico', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('11', '87941145', 'Héctor Federico', 'Guajardo', 'Delgado', '1968-06-26', 'm', 'Actor', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_natural` (`ID_PERSONA_NATURAL`, `DNI`, `NOMBRE`, `APELLIDO_PA`, `APELLIDO_MA`, `FECHA_NACIMIENTO`, `SEXO`, `PROFESION`, `created_at`, `updated_at`) VALUES ('12', '98712313', 'Juan de Dios', 'Razo', 'Loto', '1985-05-27', 'm', 'Maestro', current_date(), current_date());

INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('1', '2053885667', 'Martinez Cebolla, Azulejo', 'ARTROSCOPICTRAUMA S.A.C.', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('2', '2054950055', 'Perez Cebolla, Soledad', 'ASERCO EB EMPRESA ', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('3', '2055159793', 'Gonzales Arrugue, Estefano', 'ASOCIACION COMUNIDAD CRISTIANA EVANGELICA', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('4', '2055385645', 'Mendez Roca, Pamela', 'BI GRAND CONFECCIONES S.A.C.', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('5', '2052542677', 'Bernal Guajardo, César Luis', 'CONCEPTOS & CONSTRUCCIONES V.G EIRL', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('6', '2060115518', 'Martinez Cebolla, Azulejo', 'CORPORACION CARMINA SAC', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('7', '2055562954', 'Martinez Cebolla, Azulejo', 'CORPORACION INDUSTRIAL ALPA`C S.A.C.', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('8', '2051863992', 'Martinez Cebolla, Azulejo', 'H & J E HIJOS E.I.R.L', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('9', '2054897111', 'Martinez Cebolla, Azulejo', 'METEORO RACING SOCIEDAD ANONIMA CERRADA', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('10', '2054324898', 'Martinez Cebolla, Azulejo', 'MODAS LOREN EIRL', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('11', '2055347646', 'Martinez Cebolla, Azulejo', 'REPRESENTACIONES DIERA S.A.C.', 'sin descripcción', '2015-05-27', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`persona_juridico` (`ID_PERSONA_JURIDICO`, `RUC`, `PROPIETARIO`, `RAZON_SOCIAL`, `DESCRIPCION`, `FECHA`, `created_at`, `updated_at`) VALUES ('12', '2055374112', 'Martinez Cebolla, Azulejo', 'SERVICIOS TECNICOS EL CHALANCITO', 'sin descripcción', '2015-05-27', current_date(), current_date());

INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('966875412', 'Av. Los Jorges 567', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('963214784', 'Calle flor de mayo 092', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('932154789', 'Av. Brasil 144', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('915487896', 'Av. Morales Duarez 888', 'ninguna', '0', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('999654789', 'Calle Heroes de Cenepa 01', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('996547811', 'Urb. Los Capos de Puno 044', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('936478512', 'Av. 28 de Julio 444', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('936124789', 'Asociacion Mollepata 101', 'ninguna', '1', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('911447892', 'Av. Garzón 234', 'cerca del Areopuerto', '0', current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contribuyente` (`NUMERO_TELEFONICO`, `DIRECCION`, `REFERENCIA`, `ESTADO`, `created_at`, `updated_at`) VALUES ('978999451', 'Avenida Túpac Amaru 741', 'ninguna', '0', current_date(), current_date());

INSERT INTO `bd_impuestos_municipales`.`contrato` (`ID_CONTRATO`, `COD`, `NOMBRE`, `FECHA`, `DESCRIPCION`, `IMPUESTO`, `ID_SERVICIO`, `ID_ESTADO_CONTRATO`, `ID_CONTRIBUYENTE`, `created_at`, `updated_at`) VALUES ('1', 'A100', 'Gaseoducto Huamanguilla-Lima', "2021-02-14", 'Un gran proyecto de gaseoducto que llevara desde Huamanguilla a Lima.', '190799', '7', '1', 1, current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contrato` (`ID_CONTRATO`, `COD`, `NOMBRE`, `FECHA`, `DESCRIPCION`, `IMPUESTO`, `ID_SERVICIO`, `ID_ESTADO_CONTRATO`, `ID_CONTRIBUYENTE`,`created_at`, `updated_at`) VALUES ('2', 'B002', 'Alcantarillado en la Av. Los Linces', "2021-03-24", 'Se tiene que crear el alcantarillado faltate en esa avenida.', '56999', '2', '2', 2, current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contrato` (`ID_CONTRATO`, `COD`, `NOMBRE`, `FECHA`, `DESCRIPCION`, `IMPUESTO`, `ID_SERVICIO`, `ID_ESTADO_CONTRATO`, `ID_CONTRIBUYENTE`, `created_at`, `updated_at`) VALUES ('3', 'C001', 'Plataforma virtual', "2021-01-10", 'Se mando a realizar una plataforma para nuestra munincipalidad.', '219', '3', '2', 3, current_date(), current_date());
INSERT INTO `bd_impuestos_municipales`.`contrato` (`ID_CONTRATO`, `COD`, `NOMBRE`, `FECHA`, `DESCRIPCION`, `IMPUESTO`, `ID_SERVICIO`, `ID_ESTADO_CONTRATO`, `ID_CONTRIBUYENTE`, `created_at`, `updated_at`) VALUES ('4', '5011', 'Construccion de señales de transito faltantes', "2021-05-11", 'Las señales de transito se debe construir antes de que suceda un acccidente.', '3999', '2', '3', 4, current_date(), current_date());

use bd_impuestos_municipales;

insert into contribuyente_dni
values
(1, 1, 1, current_date(), current_date()),
(2, 2, 2, current_date(), current_date()),
(3, 3, 3, current_date(), current_date()),
(4, 4, 4, current_date(), current_date()),
(5, 5, 5, current_date(), current_date());

insert into contribuyente_ruc
values
(1, 1, 6, current_date(), current_date()),
(2, 2, 7, current_date(), current_date()),
(3, 3, 8, current_date(), current_date()),
(4, 4, 9, current_date(), current_date()),
(5, 5, 10, current_date(), current_date());

